apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    app: webserver-3
spec:
  containers:
    - name: pod3-nginx
      image: nginx:stable-alpine3.17-slim
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-volume
          mountPath: /etc/nginx/conf.d
  volumes:
    - name: html-volume
      configMap:
        name: custom-nginx-page-3
    - name: nginx-volume
      configMap:
        name: custom-nginx-conf-3
